name: Scrapy Web Scraping

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs the job every day at midnight

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scrapy spider
        run: |
          scrapy crawl merojob  # Replace <spider_name> with the name of your spider
